[extension]
name = "val3dity"
version = "0.2.0"
versionCityJSON = "2.0"
description = "Extension to store val3dity validation reports and per-geometry diagnostics."
authors = ["[Ravi Peters](https://github.com/ylannl)"]
repository = "https://github.com/cityjson/extensions"
keywords = ["validation", "geometry", "quality", "val3dity"]
license = "MIT"
